[package]
name = "generics_traits_lifetimes_structs_different_generic_05"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
